DELETE FROM employees
WHERE (LAST_NAME, DEPARTMENT_ID, salary) NOT IN (
    SELECT DISTINCT ON (LAST_NAME, DEPARTMENT_ID) LAST_NAME, DEPARTMENT_ID, salary
    FROM employees
    ORDER BY LAST_NAME, DEPARTMENT_ID, salary DESC
);
